# Diferencia entre np.matrix y np.array

Dos formas de generar matrices en python es con las funciones de **numpy matrix y array**. Las dos son una herramienta muy útil para la construcción de matrices pero son diferentes.

Las matrices de numpy **(np.matrix)** únicamente son bi-dimensionales. Es decir que solo se pueden crear tensores de dos dimensiones (rango 1). En cambio, la funcion **np.array** puede tener ***n*** dimensiones

## np.matrix

Una de las ventajas para utilizar **np.matrix** es que pueden realizar muy fácilmente operaciones matemáticas y vectoriales sobre ellas al ser bi-dimensionales. Ej. Matrix inversa, etc.

In [1]:
import numpy as np

In [2]:
mat = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [3]:
mat*2

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]])

In [4]:
mat.I

matrix([[-0.48333333, -0.24444444, -0.00555556,  0.23333333],
        [-0.03333333, -0.01111111,  0.01111111,  0.03333333],
        [ 0.41666667,  0.22222222,  0.02777778, -0.16666667]])

Pero, al intentar multiplicar por la misma matriz, no puedo hacerlo debido a que el número de columnas difiere del número de filas de la segunda matriz.

In [5]:
mat*mat

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

Una de las ventajas para utilizar **np.array** es que se pueden realizar cualquier tipo de operaciones aunque la matemática no las soporte. Lo que hace es realizar una multiplicacion elemento por elemento. Si se requiere multiplicar matricialmente, se debe de utilizar **np.dot**

In [6]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [7]:
arr1*arr1

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

Por otro lado, no contemplan las matrices inversas

In [8]:
arr.I

NameError: name 'arr' is not defined

También existe un operando llamado ***infix matrix multiplicacion (@)*** donde se logra llegar a la multiplicación matricial (igualmente con **np.dot**)

In [9]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
arr2 = np.array([
    [11,12,13],
    [14,15,16],
    [17,18,19]
])

In [10]:
print(arr1@arr2)
print(np.dot(arr1,arr2))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]
 [468 501 534]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]
 [468 501 534]]
