In [1]:
import numpy as np

**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [2]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

In [3]:
def bellman(R,P,V,gamma):
    return(R + (gamma*np.matmul(P,V)))
bellman(R,P,V,gamma)

array([10.,  2.,  5.])

### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
def relu(x):
    return(np.maximum(0,x))

In [6]:
#With sigmoid
x = np.array([1,1])
def neural_network(x):
    mat_HL = np.array([
        [0.712, 0.355, 0.268],
        [0.112, 0.855, 0.468]
    ])
    mat_OL = np.array([
        [0.116],
        [0.329],
        [0.708]
    ])
    HL = np.matmul(x,mat_HL)
    HL = sigmoid(HL)
    OL = np.matmul(HL,mat_OL)
    OL = sigmoid(OL)
    print(HL)
    return(OL)

neural_network(x)

[0.69508477 0.77029895 0.67612055]


array([0.69269553])

In [7]:
#With rectifier
x = np.array([1,1])
def neural_network(x):
    mat_HL = np.array([
        [0.712, 0.355, 0.268],
        [0.112, 0.855, 0.468]
    ])
    mat_OL = np.array([
        [0.116],
        [0.329],
        [0.708]
    ])
    HL = np.matmul(x,mat_HL)
    HL = sigmoid(HL)
    OL = np.matmul(HL,mat_OL)
    OL = relu(OL)
    print(HL)
    return(OL)

neural_network(x)

[0.69508477 0.77029895 0.67612055]


array([0.81275154])

In [8]:
## Evaluando la red sobre la matriz de datos X
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
neural_network(X)

[[0.5732687  0.85138432 0.72368206]
 [0.56561932 0.62040086 0.57224093]
 [0.98972791 0.99992287 0.9961353 ]
 [0.99990057 0.99991645 0.99758587]
 [0.99610438 0.99884211 0.98545706]
 [0.5752246  0.68793868 0.61177987]
 [0.99988879 0.99980357 0.99615067]
 [1.         1.         1.        ]
 [0.997213   0.99991084 0.99638845]
 [1.         1.         1.        ]]


array([[0.85897151],
       [0.6748703 ],
       [1.14904686],
       [1.15125178],
       [1.14187076],
       [0.72619803],
       [1.15019715],
       [1.153     ],
       [1.1500904 ],
       [1.153     ]])